[project]
name = "scraptolib"
version = "0.1.0"
description = "Educational web scraping framework using Selenium."
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "selenium>=4.39.0",
    "undetected-chromedriver>=3.5.5",
]